# Generated by Django 3.1.5 on 2021-01-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.IntegerField()),
                ('url', models.URLField(max_length=100000)),
                ('product_name', models.TextField()),
                ('Email_Id', models.EmailField(max_length=5000)),
                ('desired_price', models.FloatField()),
            ],
        ),
    ]
